version: '3'
services:
  mongodb:
    image: mongo:4.2.15
    container_name: mongo-pwndoc
    volumes:
      - ./backend/mongo-data:/data/db
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_DB=pwndoc
    networks:
      - backend

  pwndoc-backend:
    build: ./backend
    container_name: pwndoc-backend
    volumes:
      - ./backend/report-templates:/app/report-templates
      - ./backend/src/config:/app/src/config
    depends_on:
      - mongodb
    restart: always
    ports:
      - 4242:4242
    environment:
      - NODE_ENV=prod
    networks:
      - backend

  pwndoc-frontend:
    build: ./frontend
    container_name: pwndoc-frontend
    restart: always
    ports:
      - 8443:8443
    networks:
      - backend

volumes:
  mongo-data:

networks:
  backend:
    driver: bridge
